/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'articles-edit-id': RouteRecordInfo<'articles-edit-id', '/articles/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'articles-edit-hehe': RouteRecordInfo<'articles-edit-hehe', '/articles/edit/hehe', Record<never, never>, Record<never, never>>,
    'calendar': RouteRecordInfo<'calendar', '/calendar', Record<never, never>, Record<never, never>>,
    'faqs': RouteRecordInfo<'faqs', '/faqs', Record<never, never>, Record<never, never>>,
    'forms': RouteRecordInfo<'forms', '/forms', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'opinions': RouteRecordInfo<'opinions', '/opinions', Record<never, never>, Record<never, never>>,
    'pages': RouteRecordInfo<'pages', '/pages', Record<never, never>, Record<never, never>>,
    'partners': RouteRecordInfo<'partners', '/partners', Record<never, never>, Record<never, never>>,
    'products': RouteRecordInfo<'products', '/products', Record<never, never>, Record<never, never>>,
    'team-members': RouteRecordInfo<'team-members', '/team-members', Record<never, never>, Record<never, never>>,
    'testimonials': RouteRecordInfo<'testimonials', '/testimonials', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
  }
}
