/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-articles': RouteRecordInfo<'admin-articles', '/admin/articles', Record<never, never>, Record<never, never>>,
    'admin-articles-edit-id': RouteRecordInfo<'admin-articles-edit-id', '/admin/articles/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-events': RouteRecordInfo<'admin-events', '/admin/events', Record<never, never>, Record<never, never>>,
    'admin-forms': RouteRecordInfo<'admin-forms', '/admin/forms', Record<never, never>, Record<never, never>>,
    'admin-pages': RouteRecordInfo<'admin-pages', '/admin/pages', Record<never, never>, Record<never, never>>,
    'admin-partners': RouteRecordInfo<'admin-partners', '/admin/partners', Record<never, never>, Record<never, never>>,
    'admin-testimonials': RouteRecordInfo<'admin-testimonials', '/admin/testimonials', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
